// Code generated by go generate; DO NOT EDIT.

//go:build ignore

package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"strings"
)

func main() {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "opCode.go", nil, 0)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse error: %v\n", err)
		os.Exit(1)
	}

	type entry struct {
		name  string
		value string
	}
	var entries []entry

	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.CONST {
			continue
		}
		for _, spec := range gd.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok || len(vs.Names) == 0 || len(vs.Values) == 0 {
				continue
			}
			name := vs.Names[0].Name
			if !strings.HasPrefix(name, "Opcode") {
				continue
			}
			lit, ok := vs.Values[0].(*ast.BasicLit)
			if !ok {
				continue
			}
			entries = append(entries, entry{name: name, value: lit.Value})
		}
	}

	out, err := os.Create("opCode_string.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "create error: %v\n", err)
		os.Exit(1)
	}
	defer out.Close()

	fmt.Fprintln(out, "// Code generated by go generate; DO NOT EDIT.")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "package packet")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "var OpCodeStringMap = map[uint32]string{")
	for _, e := range entries {
		fmt.Fprintf(out, "\t%s: %q,\n", e.value, e.name)
	}
	fmt.Fprintln(out, "}")
}
